server:
   port: 8081
   
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/user?createDatabaseIfNotExist=true
      username: root
      password: pass
   jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate:
         ddl-auto: create
      generate-ddl: true
   security:
      user:
         name: deva
         password: pass"
logging:
  level:
    org:
      springframework:
        security: DEBUG
       
       
 